import React from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const START={lat:30.3165,lng:78.0322};
function App(){
 const [mode,setMode]=React.useState<'CAR'|'BIKE'>('CAR');
 const [speed,setSpeed]=React.useState(0); const [heading,setHeading]=React.useState(0); const [distance,setDistance]=React.useState(0);
 React.useEffect(()=>{const keys=new Set<string>(); const down=(e:KeyboardEvent)=>{keys.add(e.key.toLowerCase());}; const up=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase()); window.addEventListener('keydown',down);window.addEventListener('keyup',up);let raf=0;let last=performance.now();const tick=(now:number)=>{const dt=Math.min(.05,(now-last)/1000);last=now;let v=speed;if(keys.has('w')||keys.has('arrowup'))v=Math.min(mode==='CAR'?120:80,v+55*dt);else if(keys.has('s')||keys.has('arrowdown'))v=Math.max(0,v-90*dt);else v=Math.max(0,v-25*dt);let h=heading;if(keys.has('a')||keys.has('arrowleft'))h=(h-80*dt+360)%360;if(keys.has('d')||keys.has('arrowright'))h=(h+80*dt)%360;setSpeed(v);setHeading(h);setDistance(d=>d+v*dt/3.6);raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(raf);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[mode,speed,heading]);
 return <main className="app"><header><div><span className="eyebrow">WORLD DRIVE</span><h1>Street Driver</h1></div><div className="status">MVP • Street View</div></header><section className="viewer"><div className="notice"><strong>Street View engine ready</strong><span>Add your Google Maps API key to activate the live panorama.</span></div><div className="road"><div className="road-line"></div><div className="car">🚗</div></div><div className="hud"><div><small>SPEED</small><b>{Math.round(speed)} <em>km/h</em></b></div><div><small>HEADING</small><b>{Math.round(heading)}°</b></div><div><small>DISTANCE</small><b>{distance.toFixed(2)} <em>km</em></b></div><div><small>VEHICLE</small><div className="toggle"><button onClick={()=>setMode('CAR')} className={mode==='CAR'?'active':''}>CAR</button><button onClick={()=>setMode('BIKE')} className={mode==='BIKE'?'active':''}>BIKE</button></div></div></div></section><footer><span>WASD / Arrow Keys • Mouse look will be added with Street View</span><span>START • {START.lat}, {START.lng}</span></footer></main>}
createRoot(document.getElementById('root')!).render(<App/>);